#!/bin/bash
#
# pyIRCX Installation Script
#
# Supports: Debian/Ubuntu, RHEL/CentOS/Fedora, Arch Linux, openSUSE
#
set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Version
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INSTALL_VERSION="$(python3 -c 'import json, pathlib; print(json.load(open(pathlib.Path("'"$SCRIPT_DIR"'") / "version.json"))["version"])')"

# Default installation paths
INSTALL_DIR="/opt/pyircx"
CONFIG_DIR="/etc/pyircx"
SERVICE_USER="pyircx"
SERVICE_GROUP="pyircx"
INSTALL_CONF="/etc/pyircx/install.conf"

# Web installation paths (will be set by prompts or config)
WEB_ADMIN_DIR=""
WEBCHAT_WEB_DIR=""

# DNS resolver (will be set by prompts)
UNBOUND_INSTALLED="false"

# Generated secrets for first-time install
GENERATED_ADMIN_PASS="__CHANGE_ME__"
GENERATED_WEBIRC_PASS="__CHANGE_ME__"
NONINTERACTIVE="${PYIRCX_NONINTERACTIVE:-0}"
INSTALL_DIR_PROMPT="${PYIRCX_INSTALL_DIR_PROMPT:-yes}"
INSTALL_UNBOUND_PROMPT="${PYIRCX_INSTALL_UNBOUND:-ask}"
INSTALL_APACHE_PROMPT="${PYIRCX_INSTALL_APACHE:-ask}"
INSTALL_SSL_PROMPT="${PYIRCX_INSTALL_SSL:-ask}"
INSTALL_WEBADMIN_PROMPT="${PYIRCX_INSTALL_WEBADMIN:-ask}"
INSTALL_WEBCHAT_PROMPT="${PYIRCX_INSTALL_WEBCHAT:-ask}"

# Detect OS
detect_os() {
    if [ -f /etc/os-release ]; then
        . /etc/os-release
        OS=$ID
        VERSION=$VERSION_ID
    elif [ -f /etc/redhat-release ]; then
        OS="rhel"
    elif [ -f /etc/debian_version ]; then
        OS="debian"
    else
        OS="unknown"
    fi
    echo "$OS"
}

# Check if running as root
check_root() {
    if [ "$EUID" -ne 0 ]; then
        echo -e "${RED}Error: This script must be run as root${NC}"
        echo "Try: sudo $0"
        exit 1
    fi
}

prompt_yes_no() {
    local prompt="$1"
    local default_answer="$2"
    local configured_answer="${3:-ask}"
    local reply=""
    local normalized=""

    if [ "$NONINTERACTIVE" = "1" ] && [ "$configured_answer" != "ask" ]; then
        reply="$configured_answer"
        echo "$prompt $([ "$default_answer" = "yes" ] && echo "[Y/n]" || echo "[y/N]") $reply"
    else
        read -p "$prompt $([ "$default_answer" = "yes" ] && echo "[Y/n]" || echo "[y/N]") " -n 1 -r
        echo
        reply="${REPLY:-}"
    fi

    case "${reply,,}" in
        y|yes)
            normalized="y"
            ;;
        n|no)
            normalized="n"
            ;;
        *)
            normalized="$reply"
            ;;
    esac

    if [ "$default_answer" = "yes" ]; then
        [[ "$normalized" != "n" ]]
    else
        [[ "$normalized" = "y" ]]
    fi
}

detect_web_user() {
    if id apache &>/dev/null; then
        echo "apache"
    elif id www-data &>/dev/null; then
        echo "www-data"
    elif id http &>/dev/null; then
        echo "http"
    else
        echo ""
    fi
}

# Generate install-time secrets (fallback to placeholders if generation fails)
generate_install_secrets() {
    GENERATED_ADMIN_PASS=$(python3 -c "import secrets; print(secrets.token_urlsafe(18))" 2>/dev/null || echo "__CHANGE_ME__")
    GENERATED_WEBIRC_PASS=$(python3 -c "import secrets; print(secrets.token_urlsafe(24))" 2>/dev/null || echo "__CHANGE_ME__")
}

# Save installation configuration
save_install_config() {
    echo -e "${YELLOW}Saving installation configuration...${NC}"

    mkdir -p "$(dirname "$INSTALL_CONF")"

    cat > "$INSTALL_CONF" << EOF
# pyIRCX Installation Configuration
# Generated by install.sh on $(date)
# Used by upgrade.sh, repair.sh, and uninstall.sh

# Installation metadata
INSTALL_DATE="$(date +%Y-%m-%d)"
INSTALL_VERSION="$INSTALL_VERSION"
INSTALL_USER="$USER"

# Core installation paths
PYIRCX_DIR="$INSTALL_DIR"
CONFIG_DIR="$CONFIG_DIR"
CONFIG_FILE="$CONFIG_DIR/pyircx_config.json"

# Web components
WEBADMIN_DIR="$WEB_ADMIN_DIR"
WEBADMIN_ENABLED="$([ -n "$WEB_ADMIN_DIR" ] && echo "true" || echo "false")"

WEBCHAT_DIR="$WEBCHAT_WEB_DIR"
WEBCHAT_ENABLED="$([ -n "$WEBCHAT_WEB_DIR" ] && echo "true" || echo "false")"
WEBCHAT_GATEWAY_DIR="$INSTALL_DIR/webchat"

# Web server
WEB_USER="${WEB_USER:-$(detect_web_user)}"

# Database
DATABASE_PATH="$INSTALL_DIR/pyircx.db"

# Service
SERVICE_ENABLED="true"
SERVICE_USER="$SERVICE_USER"
SERVICE_GROUP="$SERVICE_GROUP"

# DNS
UNBOUND_ENABLED="${UNBOUND_INSTALLED:-false}"
EOF

    chmod 644 "$INSTALL_CONF"
    echo -e "${GREEN}Installation configuration saved to $INSTALL_CONF${NC}"
}

# Load installation configuration
load_install_config() {
    if [ -f "$INSTALL_CONF" ]; then
        echo -e "${YELLOW}Loading existing installation configuration...${NC}"
        source "$INSTALL_CONF"

        # Set variables from config
        WEB_ADMIN_DIR="${WEBADMIN_DIR:-}"
        WEBCHAT_WEB_DIR="${WEBCHAT_DIR:-}"

        return 0
    fi
    return 1
}

# Prompt for WebAdmin installation path
prompt_webadmin_path() {
    echo ""
    echo "========================================"
    echo "Web Administration Panel - Installation Path"
    echo "========================================"
    echo ""
    echo "Where should the Web Admin Panel be installed?"
    echo ""
    echo "Options:"
    echo "  1. /var/www/html/webadmin (recommended, subdirectory)"
    echo "  2. /var/www/html (direct in webroot)"
    echo "  3. Custom path"
    echo "  4. Skip installation"
    echo ""
    read -p "Enter choice [1-4] (default: 1): " WEBADMIN_CHOICE

    case "${WEBADMIN_CHOICE:-1}" in
        1)
            WEB_ADMIN_DIR="/var/www/html/webadmin"
            echo -e "${GREEN}WebAdmin will be installed to: $WEB_ADMIN_DIR${NC}"
            ;;
        2)
            WEB_ADMIN_DIR="/var/www/html"
            echo -e "${YELLOW}Warning: Installing directly in webroot${NC}"
            echo -e "${GREEN}WebAdmin will be installed to: $WEB_ADMIN_DIR${NC}"
            ;;
        3)
            read -p "Enter custom path: " CUSTOM_PATH
            WEB_ADMIN_DIR="${CUSTOM_PATH:-/var/www/html/webadmin}"
            echo -e "${GREEN}WebAdmin will be installed to: $WEB_ADMIN_DIR${NC}"
            ;;
        4)
            WEB_ADMIN_DIR=""
            echo -e "${YELLOW}WebAdmin installation skipped${NC}"
            ;;
        *)
            WEB_ADMIN_DIR="/var/www/html/webadmin"
            echo -e "${GREEN}WebAdmin will be installed to: $WEB_ADMIN_DIR (default)${NC}"
            ;;
    esac
}

# Prompt for WebChat installation path
prompt_webchat_path() {
    echo ""
    echo "========================================"
    echo "WebChat - Installation Path"
    echo "========================================"
    echo ""
    echo "Where should WebChat be installed?"
    echo ""
    echo "Options:"
    echo "  1. /var/www/html/webchat (recommended, subdirectory)"
    echo "  2. /var/www/html (direct in webroot)"
    echo "  3. Custom path"
    echo "  4. Skip installation"
    echo ""
    read -p "Enter choice [1-4] (default: 1): " WEBCHAT_CHOICE

    case "${WEBCHAT_CHOICE:-1}" in
        1)
            WEBCHAT_WEB_DIR="/var/www/html/webchat"
            echo -e "${GREEN}WebChat will be installed to: $WEBCHAT_WEB_DIR${NC}"
            ;;
        2)
            WEBCHAT_WEB_DIR="/var/www/html"
            echo -e "${YELLOW}Warning: Installing directly in webroot${NC}"
            echo -e "${GREEN}WebChat will be installed to: $WEBCHAT_WEB_DIR${NC}"
            ;;
        3)
            read -p "Enter custom path: " CUSTOM_PATH
            WEBCHAT_WEB_DIR="${CUSTOM_PATH:-/var/www/html/webchat}"
            echo -e "${GREEN}WebChat will be installed to: $WEBCHAT_WEB_DIR${NC}"
            ;;
        4)
            WEBCHAT_WEB_DIR=""
            echo -e "${YELLOW}WebChat installation skipped${NC}"
            ;;
        *)
            WEBCHAT_WEB_DIR="/var/www/html/webchat"
            echo -e "${GREEN}WebChat will be installed to: $WEBCHAT_WEB_DIR (default)${NC}"
            ;;
    esac
}

# Check version consistency across project files
check_version_consistency() {
    echo -e "${YELLOW}Checking version consistency...${NC}"

    SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    VERSION_ISSUES=0

    # Get version from pyircx.py
    if [ -f "$SCRIPT_DIR/pyircx.py" ]; then
        PYIRCX_VERSION=$(python3 -c 'import json, pathlib; print(json.load(open(pathlib.Path("'"$SCRIPT_DIR"'") / "version.json"))["version"])')
        echo -e "${GREEN}  version.json version: $PYIRCX_VERSION${NC}"

        # Check against INSTALL_VERSION
        if [ "$PYIRCX_VERSION" != "$INSTALL_VERSION" ]; then
            echo -e "${RED}  ✗ Version mismatch: install.sh has $INSTALL_VERSION${NC}"
            VERSION_ISSUES=$((VERSION_ISSUES + 1))
        else
            echo -e "${GREEN}  ✓ install.sh version matches${NC}"
        fi

        # Check webadmin/index.php
        if [ -f "$SCRIPT_DIR/webadmin/index.php" ]; then
            echo -e "${GREEN}  ✓ webadmin/index.php reads shared version metadata${NC}"
        fi

        # Check webchat/index.html
        if [ -f "$SCRIPT_DIR/webchat/index.html" ]; then
            echo -e "${GREEN}  ✓ webchat/index.html reads shared version metadata${NC}"
        fi

        if [ $VERSION_ISSUES -gt 0 ]; then
            echo -e "${YELLOW}  ⚠ Found $VERSION_ISSUES version inconsistency issue(s)${NC}"
            echo -e "${YELLOW}  This may indicate the installation files need to be updated${NC}"
            read -p "Continue anyway? (y/n) " -n 1 -r
            echo
            if [[ ! $REPLY =~ ^[Yy]$ ]]; then
                exit 1
            fi
        fi
    else
        echo -e "${YELLOW}  ⚠ pyircx.py not found, skipping version check${NC}"
    fi
}

# Check Python version
check_python() {
    echo -e "${YELLOW}Checking Python version...${NC}"

    if command -v python3 &> /dev/null; then
        PYTHON_VERSION=$(python3 -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')
        PYTHON_MAJOR=$(echo $PYTHON_VERSION | cut -d. -f1)
        PYTHON_MINOR=$(echo $PYTHON_VERSION | cut -d. -f2)

        if [ "$PYTHON_MAJOR" -ge 3 ] && [ "$PYTHON_MINOR" -ge 8 ]; then
            echo -e "${GREEN}Python $PYTHON_VERSION found${NC}"
            return 0
        fi
    fi

    echo -e "${RED}Error: Python 3.8+ is required${NC}"
    echo "Please install Python 3.8 or later"
    exit 1
}

# Install dependencies based on OS
install_dependencies() {
    local os=$(detect_os)
    echo -e "${YELLOW}Installing dependencies for $os...${NC}"

    if command -v python3 &>/dev/null; then
        if command -v pip3 &>/dev/null; then
            echo -e "${GREEN}Python 3 and pip3 already available, skipping package manager dependency install${NC}"
            return
        fi

        echo -e "${YELLOW}pip3 not found, attempting local bootstrap...${NC}"
        if python3 -m ensurepip --upgrade >/dev/null 2>&1; then
            echo -e "${GREEN}pip3 bootstrapped with ensurepip${NC}"
            return
        fi
    fi

    case $os in
        ubuntu|debian|linuxmint|pop|elementary|zorin|kali|parrot|raspbian)
            apt-get update
            apt-get install -y python3 python3-pip python3-venv
            ;;
        fedora)
            dnf install -y python3 python3-pip
            ;;
        centos|rhel|rocky|almalinux|oracle|scientific)
            if [ -f /etc/centos-release ] || [ "$VERSION_ID" -lt 8 ]; then
                yum install -y python3 python3-pip
            else
                dnf install -y python3 python3-pip
            fi
            ;;
        arch|manjaro|endeavouros|garuda|artix)
            pacman -Sy --noconfirm python python-pip
            ;;
        opensuse*|sles|tumbleweed)
            zypper install -y python3 python3-pip
            ;;
        gentoo|funtoo)
            emerge --ask=n dev-lang/python dev-python/pip
            ;;
        void)
            xbps-install -Sy python3 python3-pip
            ;;
        alpine)
            apk add --no-cache python3 py3-pip
            ;;
        solus)
            eopkg install -y python3 pip
            ;;
        nixos)
            echo -e "${YELLOW}NixOS detected. Please add python3 and pip to your configuration.nix${NC}"
            echo "Example: environment.systemPackages = with pkgs; [ python3 python3Packages.pip ];"
            ;;
        clear-linux-os)
            swupd bundle-add python3-basic
            ;;
        mageia)
            urpmi python3 python3-pip
            ;;
        slackware)
            # Slackware typically has Python pre-installed
            echo -e "${GREEN}Slackware detected. Python should be pre-installed.${NC}"
            if ! command -v pip3 &> /dev/null; then
                echo -e "${YELLOW}pip not found. Installing pip...${NC}"
                python3 -m ensurepip --default-pip || python3 <(curl -sS https://bootstrap.pypa.io/get-pip.py)
            fi
            ;;
        *)
            echo -e "${YELLOW}Unknown OS ($os), attempting generic installation...${NC}"
            # Try to detect package manager and install
            if command -v apt-get &> /dev/null; then
                apt-get update && apt-get install -y python3 python3-pip python3-venv
            elif command -v dnf &> /dev/null; then
                dnf install -y python3 python3-pip
            elif command -v yum &> /dev/null; then
                yum install -y python3 python3-pip
            elif command -v pacman &> /dev/null; then
                pacman -Sy --noconfirm python python-pip
            elif command -v zypper &> /dev/null; then
                zypper install -y python3 python3-pip
            elif command -v apk &> /dev/null; then
                apk add --no-cache python3 py3-pip
            elif command -v emerge &> /dev/null; then
                emerge --ask=n dev-lang/python dev-python/pip
            else
                echo -e "${YELLOW}No supported package manager found.${NC}"
                echo -e "${YELLOW}Please ensure Python 3.8+ and pip are installed manually.${NC}"
            fi
            ;;
    esac
}

# Install Python packages
install_python_packages() {
    echo -e "${YELLOW}Installing Python packages...${NC}"

    local pip_args=()

    if pip3 install --help 2>/dev/null | grep -q -- '--break-system-packages'; then
        pip_args+=(--break-system-packages)
    fi

    pip3 install "${pip_args[@]}" aiosqlite bcrypt pyotp cryptography

    echo -e "${GREEN}Python packages installed${NC}"
}

# Create service user
create_user() {
    echo -e "${YELLOW}Creating service user...${NC}"

    if id "$SERVICE_USER" &>/dev/null; then
        echo "User $SERVICE_USER already exists"
    else
        useradd --system --no-create-home --shell /usr/sbin/nologin "$SERVICE_USER"
        echo -e "${GREEN}User $SERVICE_USER created${NC}"
    fi

    # Add user to ssl-cert group for Let's Encrypt certificate access (Debian/Ubuntu)
    if getent group ssl-cert &>/dev/null; then
        if ! groups "$SERVICE_USER" 2>/dev/null | grep -q ssl-cert; then
            usermod -a -G ssl-cert "$SERVICE_USER"
            echo -e "${GREEN}User added to ssl-cert group${NC}"
        fi
    fi
}

# Create directories
create_directories() {
    echo -e "${YELLOW}Creating directories...${NC}"

    mkdir -p "$INSTALL_DIR"
    mkdir -p "$INSTALL_DIR/transcripts"
    mkdir -p "$CONFIG_DIR"

    echo -e "${GREEN}Directories created${NC}"
}

# Copy files
copy_files() {
    echo -e "${YELLOW}Copying files...${NC}"

    # Get the directory where this script is located
    SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

    # Copy main script and modules
    cp "$SCRIPT_DIR/pyircx.py" "$INSTALL_DIR/"
    cp "$SCRIPT_DIR/channel.py" "$INSTALL_DIR/"
    cp "$SCRIPT_DIR/config.py" "$INSTALL_DIR/"
    cp "$SCRIPT_DIR/database.py" "$INSTALL_DIR/"
    cp "$SCRIPT_DIR/help_text.py" "$INSTALL_DIR/"
    cp "$SCRIPT_DIR/modes.py" "$INSTALL_DIR/"
    cp "$SCRIPT_DIR/responses.py" "$INSTALL_DIR/"
    cp "$SCRIPT_DIR/security.py" "$INSTALL_DIR/"
    cp "$SCRIPT_DIR/service_bot.py" "$INSTALL_DIR/"
    cp "$SCRIPT_DIR/ssl_manager.py" "$INSTALL_DIR/"
    cp "$SCRIPT_DIR/user.py" "$INSTALL_DIR/"
    cp "$SCRIPT_DIR/validation.py" "$INSTALL_DIR/"
    cp "$SCRIPT_DIR/api.py" "$INSTALL_DIR/" 2>/dev/null || true
    cp "$SCRIPT_DIR/api_helpers.py" "$INSTALL_DIR/" 2>/dev/null || true
    cp "$SCRIPT_DIR/db_pool.py" "$INSTALL_DIR/" 2>/dev/null || true
    cp "$SCRIPT_DIR/linking.py" "$INSTALL_DIR/"

    # Copy or create config
    created_config="false"
    if [ ! -f "$CONFIG_DIR/pyircx_config.json" ]; then
        if [ -f "$SCRIPT_DIR/pyircx_config.json" ]; then
            # Use provided config template
            cp "$SCRIPT_DIR/pyircx_config.json" "$CONFIG_DIR/"
            echo "Copied config template"
            created_config="true"
        else
            # Generate default config from pyircx.py
            echo "Generating default config..."
            python3 "$SCRIPT_DIR/generate_default_config.py" "$INSTALL_DIR/pyircx.py" "$CONFIG_DIR/pyircx_config.json"
            created_config="true"
        fi
    else
        echo "Config already exists, not overwriting"
    fi

    if [ "$created_config" = "true" ]; then
        python3 - "$CONFIG_DIR/pyircx_config.json" "$GENERATED_ADMIN_PASS" "$GENERATED_WEBIRC_PASS" <<'PY'
import json
import sys

cfg_path, admin_pass, webirc_pass = sys.argv[1], sys.argv[2], sys.argv[3]

with open(cfg_path, 'r', encoding='utf-8') as f:
    cfg = json.load(f)

cfg.setdefault('admin', {})
cfg['admin']['default_password'] = admin_pass

cfg.setdefault('security', {})
cfg['security']['auth_require_ssl'] = True
cfg['security']['pass_require_ssl'] = True

cfg['security'].setdefault('webirc', {})
cfg['security']['webirc'].setdefault('hosts', {})
if not cfg['security']['webirc']['hosts']:
    cfg['security']['webirc']['hosts']['pyircx-webchat'] = {'allowed_ips': ['127.0.0.1', '::1']}
for host_cfg in cfg['security']['webirc']['hosts'].values():
    host_cfg['password'] = webirc_pass

cfg.setdefault('linking', {})
cfg['linking'].setdefault('tls', {})
cfg['linking']['tls']['enabled'] = True
cfg['linking']['tls']['required'] = True
cfg['linking']['tls']['verify'] = cfg['linking']['tls'].get('verify', True)

with open(cfg_path, 'w', encoding='utf-8') as f:
    json.dump(cfg, f, indent=2)
PY
    fi

    # Create symlink for config
    ln -sf "$CONFIG_DIR/pyircx_config.json" "$INSTALL_DIR/pyircx_config.json"

    echo -e "${GREEN}Files copied${NC}"
}

# Set permissions
set_permissions() {
    echo -e "${YELLOW}Setting permissions...${NC}"

    chown -R "$SERVICE_USER:$SERVICE_GROUP" "$INSTALL_DIR"
    chown -R "$SERVICE_USER:$SERVICE_GROUP" "$CONFIG_DIR"
    chown root:"$SERVICE_GROUP" "$CONFIG_DIR/pyircx_config.json" 2>/dev/null || true
    chmod 775 "$INSTALL_DIR"  # Group needs write for SQLite journal files
    chmod 775 "$CONFIG_DIR"  # Group needs write for web admin config edits
    chmod 750 "$INSTALL_DIR/transcripts"  # Keep transcripts private
    chmod 660 "$INSTALL_DIR/pyircx.db" 2>/dev/null || true  # Database group writable
    chmod 660 "$CONFIG_DIR/pyircx_config.json" 2>/dev/null || true  # Config group-writable (needed for webadmin)
    touch "$INSTALL_DIR/admin_commands.queue" 2>/dev/null || true  # Create admin command queue
    chmod 660 "$INSTALL_DIR/admin_commands.queue" 2>/dev/null || true  # Queue group-writable (needed for webadmin)
    chmod 755 "$INSTALL_DIR/pyircx.py"
    chmod 755 "$INSTALL_DIR/api.py" 2>/dev/null || true
    chmod 755 "$INSTALL_DIR/linking.py" 2>/dev/null || true

    # Add web server user to pyircx group for database access
    # Detect web server user (apache, www-data, or http)
    WEB_USER="$(detect_web_user)"

    if [ -n "$WEB_USER" ]; then
        echo -e "${YELLOW}Adding $WEB_USER to $SERVICE_GROUP group for database access...${NC}"
        usermod -a -G "$SERVICE_GROUP" "$WEB_USER"
        echo -e "${GREEN}✓ Web server user added to group${NC}"

        # Restart PHP-FPM to apply group membership
        if systemctl is-active --quiet php-fpm 2>/dev/null; then
            echo -e "${YELLOW}Restarting PHP-FPM to apply group membership...${NC}"
            systemctl restart php-fpm
            echo -e "${GREEN}✓ PHP-FPM restarted${NC}"
        fi
    fi

    echo -e "${GREEN}Permissions set${NC}"
}

# Install Web Admin Panel
install_web_admin() {
    echo -e "${YELLOW}Installing Web Administration Panel...${NC}"

    # Check if path is set
    if [ -z "$WEB_ADMIN_DIR" ]; then
        echo -e "${RED}Error: WEB_ADMIN_DIR not set${NC}"
        return 1
    fi

    local os=$(detect_os)
    SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

    # Install Apache and PHP based on OS
    case "$os" in
        fedora|rhel|centos|rocky|almalinux|oracle|scientific)
            echo -e "${YELLOW}Installing Apache and PHP...${NC}"
            dnf install -y httpd php php-fpm php-json php-mbstring || yum install -y httpd php php-fpm php-json php-mbstring
            systemctl enable --now httpd
            systemctl enable --now php-fpm
            ;;
        debian|ubuntu|linuxmint|pop|elementary|zorin|kali|parrot|raspbian)
            echo -e "${YELLOW}Installing Apache and PHP...${NC}"
            apt-get update
            apt-get install -y apache2 php php-fpm php-json php-mbstring
            a2enmod rewrite
            systemctl enable --now apache2
            ;;
        arch|manjaro|endeavouros|garuda)
            echo -e "${YELLOW}Installing Apache and PHP...${NC}"
            pacman -S --noconfirm apache php php-fpm
            systemctl enable --now httpd
            systemctl enable --now php-fpm
            ;;
        *)
            echo -e "${YELLOW}Please install Apache and PHP manually for your OS${NC}"
            return 1
            ;;
    esac

    # Create web admin directory
    mkdir -p "$WEB_ADMIN_DIR"

    # Copy web admin files
    if [ -d "$SCRIPT_DIR/webadmin" ]; then
        cp "$SCRIPT_DIR/webadmin"/*.php "$WEB_ADMIN_DIR/" 2>/dev/null || true
        cp "$SCRIPT_DIR/webadmin"/*.js "$WEB_ADMIN_DIR/" 2>/dev/null || true
        cp "$SCRIPT_DIR/webadmin"/*.css "$WEB_ADMIN_DIR/" 2>/dev/null || true
        cp "$SCRIPT_DIR/webadmin"/.htaccess "$WEB_ADMIN_DIR/" 2>/dev/null || true
    else
        echo -e "${RED}Web admin files not found${NC}"
        return 1
    fi

    WEB_USER="$(detect_web_user)"
    if [ -n "$WEB_USER" ]; then
        chown -R "$WEB_USER:$WEB_USER" "$WEB_ADMIN_DIR"
    fi
    chmod 755 "$WEB_ADMIN_DIR"
    chmod 644 "$WEB_ADMIN_DIR"/*.php 2>/dev/null || true
    chmod 644 "$WEB_ADMIN_DIR"/*.js 2>/dev/null || true
    chmod 644 "$WEB_ADMIN_DIR"/*.css 2>/dev/null || true
    chmod 644 "$WEB_ADMIN_DIR"/.htaccess 2>/dev/null || true

    # Add web user to systemd-journal group for log access
    if [ -n "$WEB_USER" ]; then
        usermod -a -G systemd-journal "$WEB_USER" 2>/dev/null || true
    fi

    # Configure SELinux if enabled
    if command -v getenforce &>/dev/null && [ "$(getenforce)" != "Disabled" ]; then
        echo -e "${YELLOW}SELinux detected, installing policies...${NC}"
        install_selinux
    fi

    # Install polkit rules
    install_polkit

    echo -e "${GREEN}Web Admin Panel installed successfully!${NC}"
    echo ""
    echo "Access at: http://localhost/webadmin/"
    echo "Login with your IRC staff account (administrators only)"
    echo ""
}

# Install SELinux policies
install_selinux() {
    SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

    if [ ! -d "$SCRIPT_DIR/selinux" ]; then
        echo -e "${YELLOW}SELinux policy files not found, skipping${NC}"
        return 0
    fi

    echo -e "${YELLOW}Installing SELinux policies...${NC}"

    cd "$SCRIPT_DIR/selinux"

    # Compile and install httpd-systemd policy
    if [ -f pyircx-httpd-systemd.te ]; then
        checkmodule -M -m -o pyircx-httpd-systemd.mod pyircx-httpd-systemd.te
        semodule_package -o pyircx-httpd-systemd.pp -m pyircx-httpd-systemd.mod
        semodule -i pyircx-httpd-systemd.pp
        echo -e "${GREEN}✓ httpd-systemd policy installed${NC}"
    fi

    # Compile and install httpd-journal policy
    if [ -f pyircx-httpd-journal-v3.te ]; then
        checkmodule -M -m -o pyircx-httpd-journal-v3.mod pyircx-httpd-journal-v3.te
        semodule_package -o pyircx-httpd-journal-v3.pp -m pyircx-httpd-journal-v3.mod
        semodule -i pyircx-httpd-journal-v3.pp
        echo -e "${GREEN}✓ httpd-journal policy installed${NC}"
    fi

    # Install httpd-reload policy (allows webadmin to reload pyircx service)
    if [ -f pyircx-httpd-reload.pp ]; then
        semodule -i pyircx-httpd-reload.pp
        echo -e "${GREEN}✓ httpd-reload policy installed${NC}"
    fi

    cd - > /dev/null

    # Configure SELinux file contexts (comprehensive configuration)
    if command -v semanage &> /dev/null && command -v restorecon &> /dev/null; then
        echo -e "${YELLOW}Configuring SELinux file contexts...${NC}"

        # /opt/pyircx - Main installation (read-write for web admin API)
        semanage fcontext -d -t httpd_sys_rw_content_t "/opt/pyircx(/.*)?" 2>/dev/null || true
        semanage fcontext -a -t httpd_sys_rw_content_t "/opt/pyircx(/.*)?" 2>/dev/null || true

        # /etc/pyircx - Configuration directory (read-write for web admin config editor)
        #               EXCEPT webchat.conf which needs etc_t for systemd EnvironmentFile
        semanage fcontext -d -t httpd_sys_rw_content_t "/etc/pyircx(/.*)?" 2>/dev/null || true
        semanage fcontext -a -t httpd_sys_rw_content_t "/etc/pyircx(/.*)?" 2>/dev/null || true

        # /etc/pyircx/webchat.conf - SystemD EnvironmentFile (MUST be etc_t, NOT httpd_sys_rw_content_t)
        # This overrides the previous rule specifically for webchat.conf
        semanage fcontext -d -t etc_t "/etc/pyircx/webchat\.conf" 2>/dev/null || true
        semanage fcontext -a -t etc_t "/etc/pyircx/webchat\.conf" 2>/dev/null || true

        # WebAdmin - only if directory exists or will be created
        if [ -n "$WEB_ADMIN_DIR" ] || [ -d "/var/www/html/webadmin" ]; then
            ADMIN_PATH="${WEB_ADMIN_DIR:-/var/www/html/webadmin}"
            semanage fcontext -d -t httpd_sys_rw_content_t "$ADMIN_PATH(/.*)?" 2>/dev/null || true
            semanage fcontext -a -t httpd_sys_rw_content_t "$ADMIN_PATH(/.*)?" 2>/dev/null || true
        fi

        # WebChat - only if directory exists or will be created
        if [ -n "$WEBCHAT_WEB_DIR" ] || [ -d "/var/www/html/webchat" ]; then
            CHAT_PATH="${WEBCHAT_WEB_DIR:-/var/www/html/webchat}"
            semanage fcontext -d -t httpd_sys_content_t "$CHAT_PATH(/.*)?" 2>/dev/null || true
            semanage fcontext -a -t httpd_sys_content_t "$CHAT_PATH(/.*)?" 2>/dev/null || true
        fi

        # Apply all contexts
        restorecon -Rv /opt/pyircx 2>/dev/null || true
        restorecon -Rv /etc/pyircx 2>/dev/null || true
        [ -n "$WEB_ADMIN_DIR" ] && [ -d "$WEB_ADMIN_DIR" ] && restorecon -Rv "$WEB_ADMIN_DIR" 2>/dev/null || true
        [ -n "$WEBCHAT_WEB_DIR" ] && [ -d "$WEBCHAT_WEB_DIR" ] && restorecon -Rv "$WEBCHAT_WEB_DIR" 2>/dev/null || true

        # CRITICAL: Explicitly fix webchat.conf after global restorecon
        if [ -f "/etc/pyircx/webchat.conf" ]; then
            chcon -t etc_t "/etc/pyircx/webchat.conf" 2>/dev/null || true
            echo -e "${GREEN}✓ SELinux context fixed for webchat.conf (etc_t)${NC}"
        fi

        echo -e "${GREEN}✓ SELinux file contexts configured${NC}"
    fi

    echo -e "${GREEN}SELinux policies installed${NC}"
}

# Install Unbound DNS resolver
install_unbound() {
    echo -e "${YELLOW}Installing Unbound DNS resolver...${NC}"

    local os=$(detect_os)

    # Install unbound based on OS
    case "$os" in
        ubuntu|debian|linuxmint|pop|elementary|zorin|kali|parrot|raspbian)
            apt-get update
            apt-get install -y unbound
            ;;
        fedora)
            dnf install -y unbound
            ;;
        centos|rhel|rocky|almalinux|oracle|scientific)
            if [ -f /etc/centos-release ] || [ "$VERSION_ID" -lt 8 ]; then
                yum install -y unbound
            else
                dnf install -y unbound
            fi
            ;;
        arch|manjaro|endeavouros|garuda|artix)
            pacman -Sy --noconfirm unbound
            ;;
        opensuse*|sles|tumbleweed)
            zypper install -y unbound
            ;;
        gentoo|funtoo)
            emerge --ask=n net-dns/unbound
            ;;
        void)
            xbps-install -Sy unbound
            ;;
        alpine)
            apk add --no-cache unbound
            ;;
        *)
            echo -e "${YELLOW}Unknown OS ($os), attempting generic installation...${NC}"
            if command -v apt-get &> /dev/null; then
                apt-get update && apt-get install -y unbound
            elif command -v dnf &> /dev/null; then
                dnf install -y unbound
            elif command -v yum &> /dev/null; then
                yum install -y unbound
            elif command -v pacman &> /dev/null; then
                pacman -Sy --noconfirm unbound
            elif command -v zypper &> /dev/null; then
                zypper install -y unbound
            elif command -v apk &> /dev/null; then
                apk add --no-cache unbound
            else
                echo -e "${RED}No supported package manager found for unbound installation${NC}"
                return 1
            fi
            ;;
    esac

    # Create unbound configuration for local caching resolver
    echo -e "${YELLOW}Configuring unbound as local resolver...${NC}"

    # Create unbound.conf.d directory if it doesn't exist
    mkdir -p /etc/unbound/unbound.conf.d

    # Backup existing config if present
    if [ -f /etc/unbound/unbound.conf ]; then
        cp /etc/unbound/unbound.conf /etc/unbound/unbound.conf.backup.$(date +%Y%m%d%H%M%S)
    fi

    # Create pyircx-specific unbound configuration
    cat > /etc/unbound/unbound.conf.d/pyircx.conf << 'EOF'
# pyIRCX Unbound Configuration
# Local caching DNS resolver for IRC hostname resolution

server:
    # Listen on localhost (127.0.0.53 to avoid conflicts with systemd-resolved)
    interface: 127.0.0.53
    port: 53

    # Access control - only allow localhost
    access-control: 127.0.0.0/8 allow
    access-control: ::1/128 allow

    # Performance settings
    num-threads: 2
    msg-cache-size: 16m
    rrset-cache-size: 32m
    cache-min-ttl: 300
    cache-max-ttl: 86400

    # Privacy settings - don't send client info upstream
    hide-identity: yes
    hide-version: yes
    qname-minimisation: yes

    # Security settings
    harden-glue: yes
    harden-dnssec-stripped: yes
    harden-referral-path: yes
    use-caps-for-id: yes

    # Logging (minimal for production)
    verbosity: 1
    log-queries: no

    # Root hints for recursive resolution
    root-hints: "/var/lib/unbound/root.hints"

    # Enable prefetching for better performance
    prefetch: yes
    prefetch-key: yes
EOF

    # Ensure main config includes the conf.d directory
    if ! grep -q "include.*unbound.conf.d" /etc/unbound/unbound.conf 2>/dev/null; then
        echo 'include: "/etc/unbound/unbound.conf.d/*.conf"' >> /etc/unbound/unbound.conf
    fi

    # Download root hints if not present
    if [ ! -f /var/lib/unbound/root.hints ]; then
        echo -e "${YELLOW}Downloading root hints...${NC}"
        mkdir -p /var/lib/unbound
        if command -v wget &> /dev/null; then
            wget -q -O /var/lib/unbound/root.hints https://www.internic.net/domain/named.root
        elif command -v curl &> /dev/null; then
            curl -s -o /var/lib/unbound/root.hints https://www.internic.net/domain/named.root
        else
            echo -e "${YELLOW}Could not download root hints (no wget/curl). Using system defaults.${NC}"
        fi
        chown unbound:unbound /var/lib/unbound/root.hints 2>/dev/null || true
    fi

    # Set permissions
    chown -R unbound:unbound /etc/unbound/unbound.conf.d 2>/dev/null || true
    chmod 644 /etc/unbound/unbound.conf.d/pyircx.conf

    # Check configuration
    echo -e "${YELLOW}Checking unbound configuration...${NC}"
    if unbound-checkconf 2>/dev/null; then
        echo -e "${GREEN}✓ Unbound configuration is valid${NC}"
    else
        echo -e "${RED}⚠ Unbound configuration check failed, using defaults${NC}"
        rm -f /etc/unbound/unbound.conf.d/pyircx.conf
    fi

    # Enable and start unbound
    echo -e "${YELLOW}Enabling unbound service...${NC}"
    systemctl enable unbound
    systemctl restart unbound

    if systemctl is-active --quiet unbound; then
        echo -e "${GREEN}✓ Unbound is running${NC}"
    else
        echo -e "${RED}⚠ Unbound failed to start. Check: journalctl -u unbound${NC}"
        return 1
    fi

    # Configure system to use unbound for DNS
    echo -e "${YELLOW}Configuring system to use unbound for DNS resolution...${NC}"

    # Detect init system and DNS management
    if command -v resolvectl &> /dev/null && systemctl is-active --quiet systemd-resolved; then
        # systemd-resolved is active - configure it to use unbound
        echo -e "${YELLOW}Configuring systemd-resolved to use unbound...${NC}"

        mkdir -p /etc/systemd/resolved.conf.d
        cat > /etc/systemd/resolved.conf.d/unbound.conf << 'EOF'
[Resolve]
DNS=127.0.0.1
DNSStubListener=no
EOF
        systemctl restart systemd-resolved

        # Write a static resolv.conf pointing only to unbound.
        # Interface-level DHCP DNS servers would otherwise take precedence in the
        # uplink resolv.conf and bypass unbound entirely (including Spamhaus XBL,
        # which returns 127.255.255.254 "policy" responses for public resolvers).
        rm -f /etc/resolv.conf
        printf 'nameserver 127.0.0.1\n' > /etc/resolv.conf
        chattr +i /etc/resolv.conf 2>/dev/null || true

        echo -e "${GREEN}✓ systemd-resolved configured to use unbound${NC}"

    elif [ -f /etc/NetworkManager/NetworkManager.conf ] && systemctl is-active --quiet NetworkManager; then
        # NetworkManager is active - configure it to use unbound
        echo -e "${YELLOW}Configuring NetworkManager to use unbound...${NC}"

        mkdir -p /etc/NetworkManager/conf.d
        cat > /etc/NetworkManager/conf.d/unbound.conf << 'EOF'
[main]
dns=none
EOF
        # Set resolv.conf to use unbound
        cat > /etc/resolv.conf << 'EOF'
# Generated by pyIRCX install.sh for unbound
nameserver 127.0.0.53
EOF
        chattr +i /etc/resolv.conf 2>/dev/null || true
        systemctl restart NetworkManager

        echo -e "${GREEN}✓ NetworkManager configured to use unbound${NC}"

    else
        # Direct resolv.conf modification
        echo -e "${YELLOW}Configuring /etc/resolv.conf to use unbound...${NC}"

        # Backup existing resolv.conf
        if [ -f /etc/resolv.conf ] && [ ! -L /etc/resolv.conf ]; then
            cp /etc/resolv.conf /etc/resolv.conf.backup.$(date +%Y%m%d%H%M%S)
        fi

        # Check if resolv.conf is immutable
        if lsattr /etc/resolv.conf 2>/dev/null | grep -q 'i'; then
            chattr -i /etc/resolv.conf 2>/dev/null || true
        fi

        cat > /etc/resolv.conf << 'EOF'
# Generated by pyIRCX install.sh for unbound
nameserver 127.0.0.53
EOF
        chattr +i /etc/resolv.conf 2>/dev/null || true

        echo -e "${GREEN}✓ /etc/resolv.conf configured to use unbound${NC}"
    fi

    # Test DNS resolution
    echo -e "${YELLOW}Testing DNS resolution...${NC}"
    if host google.com 127.0.0.53 &>/dev/null || dig @127.0.0.53 google.com +short &>/dev/null; then
        echo -e "${GREEN}✓ DNS resolution via unbound is working${NC}"
    else
        echo -e "${YELLOW}⚠ DNS test failed - unbound may need additional configuration${NC}"
        echo "  Check: journalctl -u unbound"
        echo "  Test: dig @127.0.0.53 google.com"
    fi

    echo -e "${GREEN}Unbound DNS resolver installed and configured!${NC}"
    echo ""
    echo "Unbound configuration: /etc/unbound/unbound.conf.d/pyircx.conf"
    echo "Service commands:"
    echo "  systemctl status unbound   - Check status"
    echo "  systemctl restart unbound  - Restart resolver"
    echo ""
}

# Install Polkit rules
install_polkit() {
    SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

    if [ ! -d "$SCRIPT_DIR/polkit" ]; then
        echo -e "${YELLOW}Polkit rules not found, skipping${NC}"
        return 0
    fi

    echo -e "${YELLOW}Installing Polkit authorization rules...${NC}"

    # Copy polkit rules
    if [ -f "$SCRIPT_DIR/polkit/10-pyircx-admin.rules" ]; then
        cp "$SCRIPT_DIR/polkit/10-pyircx-admin.rules" /etc/polkit-1/rules.d/
        chown root:root /etc/polkit-1/rules.d/10-pyircx-admin.rules
        chmod 644 /etc/polkit-1/rules.d/10-pyircx-admin.rules

        # Reload polkit
        systemctl reload polkit 2>/dev/null || true

        echo -e "${GREEN}Polkit rules installed${NC}"
    fi
}


# Initialize database
initialize_database() {
    echo -e "${YELLOW}Initializing database...${NC}"

    SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    DB_PATH="$INSTALL_DIR/pyircx.db"

    # Check if database already exists
    if [ -f "$DB_PATH" ]; then
        echo -e "${YELLOW}Database already exists, skipping initialization${NC}"
        return 0
    fi

    # Use init_database.py if available
    if [ -f "$SCRIPT_DIR/init_database.py" ]; then
        echo -e "${YELLOW}Creating database with init_database.py...${NC}"
        python3 "$SCRIPT_DIR/init_database.py" "$DB_PATH" --admin-username admin --admin-password "$GENERATED_ADMIN_PASS"

        # Set ownership and permissions
        chown "$SERVICE_USER:$SERVICE_GROUP" "$DB_PATH"
        chmod 660 "$DB_PATH"

        echo -e "${GREEN}✓ Database initialized${NC}"
    else
        echo -e "${YELLOW}⚠ init_database.py not found${NC}"
        echo -e "${YELLOW}Database will be created on first service start${NC}"
    fi
}

# Install systemd service
install_systemd() {
    echo -e "${YELLOW}Installing systemd service...${NC}"

    SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

    # Copy service file
    cp "$SCRIPT_DIR/pyircx.service" /etc/systemd/system/

    # Copy certbot renewal service/timer if available
    if [ -f "$SCRIPT_DIR/pyircx-certbot-renew.service" ]; then
        cp "$SCRIPT_DIR/pyircx-certbot-renew.service" /etc/systemd/system/
        cp "$SCRIPT_DIR/pyircx-certbot-renew.timer" /etc/systemd/system/
    fi

    # Reload systemd
    systemctl daemon-reload

    # Enable service (but don't start yet - will start after database is ready)
    systemctl enable pyircx

    echo -e "${GREEN}Systemd service installed${NC}"
}

# Start pyIRCX service
start_service() {
    echo -e "${YELLOW}Starting pyIRCX service...${NC}"

    systemctl start pyircx
    sleep 2

    if systemctl is-active --quiet pyircx; then
        echo -e "${GREEN}✓ Service started successfully${NC}"
        # Fix database permissions after service access
        chmod 660 "$INSTALL_DIR/pyircx.db" 2>/dev/null || true
        chmod 775 "$INSTALL_DIR" 2>/dev/null || true
    else
        echo -e "${RED}✗ Service failed to start${NC}"
        echo -e "${YELLOW}Check logs: journalctl -u pyircx -n 50${NC}"
        return 1
    fi

    echo ""
    echo "Service commands:"
    echo "  systemctl status pyircx   - Check status"
    echo "  systemctl restart pyircx  - Restart server"
    echo "  systemctl stop pyircx     - Stop server"
}

# Install WebChat browser client
install_webchat() {
    echo -e "${YELLOW}Installing WebChat browser client...${NC}"

    # Check if path is set
    if [ -z "$WEBCHAT_WEB_DIR" ]; then
        echo -e "${RED}Error: WEBCHAT_WEB_DIR not set${NC}"
        return 1
    fi

    SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

    # Check for websockets Python module
    if ! python3 -c "import websockets" 2>/dev/null; then
        echo -e "${YELLOW}Installing Python websockets module...${NC}"
        pip3 install websockets
    fi

    # Create webchat backend directory
    mkdir -p "$INSTALL_DIR/webchat"

    # Create webchat web directory
    mkdir -p "$WEBCHAT_WEB_DIR"

    # Copy webchat files
    if [ -d "$SCRIPT_DIR/webchat" ]; then
        # Backend gateway goes to /opt/pyircx/webchat
        cp "$SCRIPT_DIR/webchat/gateway.py" "$INSTALL_DIR/webchat/"
        chmod 755 "$INSTALL_DIR/webchat/gateway.py"

        # Frontend files go to /var/www/html/webchat
        cp "$SCRIPT_DIR/webchat/index.html" "$WEBCHAT_WEB_DIR/"
        cp "$SCRIPT_DIR/webchat/config.js" "$WEBCHAT_WEB_DIR/"
        cp "$SCRIPT_DIR/webchat/favicon.svg" "$WEBCHAT_WEB_DIR/" 2>/dev/null || true
        cp "$SCRIPT_DIR/version.json" "$WEBCHAT_WEB_DIR/" 2>/dev/null || true
        chmod 644 "$WEBCHAT_WEB_DIR/index.html"
        chmod 644 "$WEBCHAT_WEB_DIR/config.js"
        chmod 644 "$WEBCHAT_WEB_DIR/favicon.svg" 2>/dev/null || true
        chmod 644 "$WEBCHAT_WEB_DIR/version.json" 2>/dev/null || true
    else
        echo -e "${RED}WebChat files not found in $SCRIPT_DIR/webchat${NC}"
        return 1
    fi

    # Set permissions
    chown -R "$SERVICE_USER:$SERVICE_GROUP" "$INSTALL_DIR/webchat"

    # Set web directory permissions (web server user)
    WEB_USER="$(detect_web_user)"
    if [ -n "$WEB_USER" ]; then
        chown -R "$WEB_USER:$WEB_USER" "$WEBCHAT_WEB_DIR"
    fi

    # Create webchat config file
    if [ ! -f "$CONFIG_DIR/webchat.conf" ]; then
        cp "$SCRIPT_DIR/webchat/webchat.conf.example" "$CONFIG_DIR/webchat.conf"
        python3 - "$CONFIG_DIR/webchat.conf" "$GENERATED_WEBIRC_PASS" <<'PY'
from pathlib import Path
import configparser
import sys

config_path = Path(sys.argv[1])
webirc_password = sys.argv[2]

cfg = configparser.ConfigParser()
cfg.read(config_path)

if not cfg.has_section('webirc'):
    cfg.add_section('webirc')
cfg.set('webirc', 'password', webirc_password)

with config_path.open('w', encoding='utf-8') as fh:
    cfg.write(fh)
PY
        chown "$SERVICE_USER:$SERVICE_GROUP" "$CONFIG_DIR/webchat.conf"
        chmod 640 "$CONFIG_DIR/webchat.conf"
    fi

    # Copy systemd service
    if [ -f "$SCRIPT_DIR/pyircx-webchat.service" ]; then
        cp "$SCRIPT_DIR/pyircx-webchat.service" /etc/systemd/system/
        systemctl daemon-reload
        # Enable and start the webchat service
        systemctl enable pyircx-webchat
        systemctl start pyircx-webchat
    fi

    # Configure firewall for WebSocket port
    if command -v firewall-cmd &>/dev/null; then
        echo -e "${YELLOW}Configuring firewall for WebChat...${NC}"
        firewall-cmd --permanent --add-port=8765/tcp 2>/dev/null || true
        firewall-cmd --reload 2>/dev/null || true
    elif command -v ufw &>/dev/null; then
        ufw allow 8765/tcp 2>/dev/null || true
    fi

    echo -e "${GREEN}WebChat installed and started!${NC}"
    echo ""
    echo "WebChat backend: $INSTALL_DIR/webchat/"
    echo "WebChat frontend: $WEBCHAT_WEB_DIR/"
    echo "Configuration: $CONFIG_DIR/webchat.conf"
    echo ""
    echo "Service commands:"
    echo "  systemctl status pyircx-webchat   - Check status"
    echo "  systemctl restart pyircx-webchat  - Restart gateway"
    echo ""
    echo "Access WebChat at: http://localhost/webchat/"
    echo "WebSocket endpoint: ws://localhost:8765"
    echo ""
    echo "For HTTPS/WSS setup, see: apache/ssl-webchat.conf.example"
    echo ""
}

# Main installation
main() {
    echo ""
    echo "========================================"
    echo "  pyIRCX Installation Script"
    echo "========================================"
    echo ""

    check_root
    check_python
    check_version_consistency
    generate_install_secrets

    echo ""
    if ! prompt_yes_no "Install to $INSTALL_DIR?" "yes" "$INSTALL_DIR_PROMPT"; then
        read -p "Enter installation directory: " INSTALL_DIR
    fi

    install_dependencies
    install_python_packages
    create_user
    create_directories
    copy_files
    set_permissions
    initialize_database
    install_systemd
    start_service

    echo ""
    echo "========================================"
    echo -e "${GREEN}  Core Installation Complete!${NC}"
    echo "========================================"
    echo ""
    echo "Configuration: $CONFIG_DIR/pyircx_config.json"
    echo "Installation:  $INSTALL_DIR"
    echo "Database:      $INSTALL_DIR/pyircx.db"
    echo "Logs:          journalctl -u pyircx -f"
    echo ""
    echo -e "${YELLOW}Default Admin Account:${NC}"
    echo "  Username: admin"
    echo "  Password: $GENERATED_ADMIN_PASS"
    echo ""
    echo -e "${RED}*** CHANGE THE DEFAULT PASSWORD IMMEDIATELY ***${NC}"
    echo ""
    echo "How to change passwords:"
    echo "  Option 1 - Password management script (RECOMMENDED):"
    echo "    cd /usr/src/pyIRCX"
    echo "    sudo ./change_password.sh staff admin      # Change admin password"
    echo "    sudo ./change_password.sh all              # Interactive mode for all passwords"
    echo ""
    echo "  Option 2 - Via command line:"
    echo "    python3 $INSTALL_DIR/api.py change-staff-password admin YourNewPassword"
    echo ""
    echo "  Option 3 - Via IRC client:"
    echo "    /QUOTE PASS admin:$GENERATED_ADMIN_PASS"
    echo "    /STAFF PASS admin YourNewPassword"
    echo ""
    echo "  The change_password.sh script can also change:"
    echo "    - WEBIRC gateway password"
    echo "    - WebChat gateway password"
    echo "    - WebAdmin password"
    echo ""
    echo -e "${GREEN}Essential Commands:${NC}"
    echo "  systemctl status pyircx   - Check server status"
    echo "  systemctl restart pyircx  - Restart server"
    echo "  systemctl stop pyircx     - Stop server"
    echo "  journalctl -u pyircx -f   - View live logs"
    echo ""
    echo -e "${GREEN}Database Management:${NC}"
    echo "  Regenerate database: python3 init_database.py $INSTALL_DIR/pyircx.db --force"
    echo "  Backup database: cp $INSTALL_DIR/pyircx.db backup_$(date +%Y%m%d).db"
    echo ""
    echo "Default IRC ports: 6667 (plain), 6697 (SSL if configured)"
    echo ""
    echo -e "${RED}⚠ SECURITY NOTICE${NC}"
    echo "  SSL authentication is currently DISABLED for easier initial setup."
    echo "  After configuring SSL, enable it in $CONFIG_DIR/pyircx_config.json:"
    echo "    \"auth_require_ssl\": true"
    echo ""
    echo "  This will require staff authentication over encrypted connections only."
    echo "  Run: sudo ./setup_ssl.sh to configure SSL/TLS"
    echo ""
    echo "========================================"
    echo -e "${YELLOW}Optional: Local DNS Resolver (Unbound)${NC}"
    echo "========================================"
    echo ""
    echo "Unbound is a fast, secure caching DNS resolver."
    echo "Installing it provides:"
    echo "  - Faster DNS lookups for hostname resolution"
    echo "  - Local caching to reduce external DNS queries"
    echo "  - Privacy - queries don't go through ISP DNS"
    echo "  - DNSSEC validation for security"
    echo ""
    if prompt_yes_no "Install Unbound DNS resolver on localhost?" "yes" "$INSTALL_UNBOUND_PROMPT"; then
        install_unbound
        UNBOUND_INSTALLED="true"
    else
        echo ""
        echo "Unbound installation skipped."
        echo "You can install it later manually if needed."
        UNBOUND_INSTALLED="false"
    fi

    echo ""
    echo "========================================"
    echo -e "${YELLOW}Optional: Web Server Setup (Apache/httpd)${NC}"
    echo "========================================"
    echo ""
    echo "Setting up Apache/httpd is recommended before SSL configuration."
    echo "This configures Apache for WebChat, WebAdmin, and SSL certificates."
    echo ""
    echo "The setup script will:"
    echo "  - Install Apache/httpd and PHP (if needed)"
    echo "  - Configure virtual hosts for WebChat and WebAdmin"
    echo "  - Set up proper permissions and SELinux contexts"
    echo "  - Enable required Apache modules"
    echo ""
    if prompt_yes_no "Set up Apache/httpd now?" "yes" "$INSTALL_APACHE_PROMPT"; then
        if [ -f "setup_apache.sh" ]; then
            echo ""
            echo "Running Apache setup..."
            ./setup_apache.sh
        else
            echo -e "${YELLOW}setup_apache.sh not found in current directory${NC}"
            echo "You can run it later: sudo ./setup_apache.sh"
        fi
    else
        echo ""
        echo "Apache setup skipped. You can run it later with:"
        echo "  sudo ./setup_apache.sh"
    fi
    echo ""
    echo "========================================"
    echo -e "${YELLOW}Optional: SSL/TLS Certificate Setup${NC}"
    echo "========================================"
    echo ""
    echo "Would you like to set up SSL/TLS now?"
    echo "  - Let's Encrypt (free, automatic)"
    echo "  - Self-signed (for testing)"
    echo "  - Skip (configure manually later)"
    echo ""
    if prompt_yes_no "Set up SSL/TLS now?" "no" "$INSTALL_SSL_PROMPT"; then
        if [ -f "setup_ssl.sh" ]; then
            ./setup_ssl.sh "$CONFIG_DIR/pyircx_config.json"
        else
            echo -e "${YELLOW}setup_ssl.sh not found, skipping SSL setup${NC}"
            echo "You can run it later: sudo ./setup_ssl.sh"
        fi
    else
        echo ""
        echo "SSL/TLS can be set up later with:"
        echo "  sudo ./setup_ssl.sh"
    fi
    echo ""
    echo "========================================"
    echo -e "${YELLOW}Optional: Web Administration Panel${NC}"
    echo "========================================"
    echo ""
    echo "The Web Admin Panel provides a browser-based interface for"
    echo "managing the IRC server. Requires Apache and PHP."
    echo ""
    if prompt_yes_no "Install Web Administration Panel?" "no" "$INSTALL_WEBADMIN_PROMPT"; then
        prompt_webadmin_path
        if [ -n "$WEB_ADMIN_DIR" ]; then
            install_web_admin
        fi
    fi

    echo ""
    echo "========================================"
    echo -e "${YELLOW}Optional: WebChat (Browser IRC Client)${NC}"
    echo "========================================"
    echo ""
    echo "WebChat provides a browser-based IRC client that connects"
    echo "via WebSocket. Requires a web server for HTTPS."
    echo ""
    if prompt_yes_no "Install WebChat browser client?" "no" "$INSTALL_WEBCHAT_PROMPT"; then
        prompt_webchat_path
        if [ -n "$WEBCHAT_WEB_DIR" ]; then
            install_webchat
        fi
    fi

    # Save installation configuration
    save_install_config
}

# Uninstall function
uninstall() {
    echo ""
    echo "========================================"
    echo "  pyIRCX Uninstallation"
    echo "========================================"
    echo ""

    check_root

    echo -e "${YELLOW}Stopping service...${NC}"
    systemctl stop pyircx 2>/dev/null || true
    systemctl disable pyircx 2>/dev/null || true

    echo -e "${YELLOW}Removing files...${NC}"
    rm -f /etc/systemd/system/pyircx.service
    systemctl daemon-reload

    read -p "Remove installation directory $INSTALL_DIR? [y/N] " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        rm -rf "$INSTALL_DIR"
    fi

    read -p "Remove configuration $CONFIG_DIR? [y/N] " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        rm -rf "$CONFIG_DIR"
    fi

    read -p "Remove user $SERVICE_USER? [y/N] " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        userdel "$SERVICE_USER" 2>/dev/null || true
    fi

    echo -e "${GREEN}Uninstallation complete${NC}"
}

# Parse arguments
case "${1:-}" in
    uninstall|remove)
        uninstall
        ;;
    *)
        main
        ;;
esac
