#!/bin/bash
#
# pyIRCX Installation Script
#
# Supports: Debian/Ubuntu, RHEL/CentOS/Fedora, Arch Linux, openSUSE
#
set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Default installation paths
INSTALL_DIR="/opt/pyircx"
CONFIG_DIR="/etc/pyircx"
SERVICE_USER="pyircx"
SERVICE_GROUP="pyircx"
INSTALL_CONF="/etc/pyircx/install.conf"

# Web installation paths (will be set by prompts or config)
WEB_ADMIN_DIR=""
WEBCHAT_WEB_DIR=""

# Detect OS
detect_os() {
    if [ -f /etc/os-release ]; then
        . /etc/os-release
        OS=$ID
        VERSION=$VERSION_ID
    elif [ -f /etc/redhat-release ]; then
        OS="rhel"
    elif [ -f /etc/debian_version ]; then
        OS="debian"
    else
        OS="unknown"
    fi
    echo "$OS"
}

# Check if running as root
check_root() {
    if [ "$EUID" -ne 0 ]; then
        echo -e "${RED}Error: This script must be run as root${NC}"
        echo "Try: sudo $0"
        exit 1
    fi
}

# Save installation configuration
save_install_config() {
    echo -e "${YELLOW}Saving installation configuration...${NC}"

    mkdir -p "$(dirname "$INSTALL_CONF")"

    cat > "$INSTALL_CONF" << EOF
# pyIRCX Installation Configuration
# Generated by install.sh on $(date)
# Used by upgrade.sh, repair.sh, and uninstall.sh

# Installation metadata
INSTALL_DATE="$(date +%Y-%m-%d)"
INSTALL_VERSION="2.0.0"
INSTALL_USER="$USER"

# Core installation paths
PYIRCX_DIR="$INSTALL_DIR"
CONFIG_DIR="$CONFIG_DIR"
CONFIG_FILE="$CONFIG_DIR/pyircx_config.json"

# Web components
WEBADMIN_DIR="$WEB_ADMIN_DIR"
WEBADMIN_ENABLED="$([ -n "$WEB_ADMIN_DIR" ] && echo "true" || echo "false")"

WEBCHAT_DIR="$WEBCHAT_WEB_DIR"
WEBCHAT_ENABLED="$([ -n "$WEBCHAT_WEB_DIR" ] && echo "true" || echo "false")"
WEBCHAT_GATEWAY_DIR="$INSTALL_DIR/webchat"

# Web server
WEB_USER="${WEB_USER:-apache}"

# Database
DATABASE_PATH="$INSTALL_DIR/pyircx.db"

# Service
SERVICE_ENABLED="true"
SERVICE_USER="$SERVICE_USER"
SERVICE_GROUP="$SERVICE_GROUP"
EOF

    chmod 644 "$INSTALL_CONF"
    echo -e "${GREEN}Installation configuration saved to $INSTALL_CONF${NC}"
}

# Load installation configuration
load_install_config() {
    if [ -f "$INSTALL_CONF" ]; then
        echo -e "${YELLOW}Loading existing installation configuration...${NC}"
        source "$INSTALL_CONF"

        # Set variables from config
        WEB_ADMIN_DIR="${WEBADMIN_DIR:-}"
        WEBCHAT_WEB_DIR="${WEBCHAT_DIR:-}"

        return 0
    fi
    return 1
}

# Prompt for WebAdmin installation path
prompt_webadmin_path() {
    echo ""
    echo "========================================"
    echo "Web Administration Panel - Installation Path"
    echo "========================================"
    echo ""
    echo "Where should the Web Admin Panel be installed?"
    echo ""
    echo "Options:"
    echo "  1. /var/www/html/webadmin (recommended, subdirectory)"
    echo "  2. /var/www/html (direct in webroot)"
    echo "  3. Custom path"
    echo "  4. Skip installation"
    echo ""
    read -p "Enter choice [1-4] (default: 1): " WEBADMIN_CHOICE

    case "${WEBADMIN_CHOICE:-1}" in
        1)
            WEB_ADMIN_DIR="/var/www/html/webadmin"
            echo -e "${GREEN}WebAdmin will be installed to: $WEB_ADMIN_DIR${NC}"
            ;;
        2)
            WEB_ADMIN_DIR="/var/www/html"
            echo -e "${YELLOW}Warning: Installing directly in webroot${NC}"
            echo -e "${GREEN}WebAdmin will be installed to: $WEB_ADMIN_DIR${NC}"
            ;;
        3)
            read -p "Enter custom path: " CUSTOM_PATH
            WEB_ADMIN_DIR="${CUSTOM_PATH:-/var/www/html/webadmin}"
            echo -e "${GREEN}WebAdmin will be installed to: $WEB_ADMIN_DIR${NC}"
            ;;
        4)
            WEB_ADMIN_DIR=""
            echo -e "${YELLOW}WebAdmin installation skipped${NC}"
            ;;
        *)
            WEB_ADMIN_DIR="/var/www/html/webadmin"
            echo -e "${GREEN}WebAdmin will be installed to: $WEB_ADMIN_DIR (default)${NC}"
            ;;
    esac
}

# Prompt for WebChat installation path
prompt_webchat_path() {
    echo ""
    echo "========================================"
    echo "WebChat - Installation Path"
    echo "========================================"
    echo ""
    echo "Where should WebChat be installed?"
    echo ""
    echo "Options:"
    echo "  1. /var/www/html/webchat (recommended, subdirectory)"
    echo "  2. /var/www/html (direct in webroot)"
    echo "  3. Custom path"
    echo "  4. Skip installation"
    echo ""
    read -p "Enter choice [1-4] (default: 1): " WEBCHAT_CHOICE

    case "${WEBCHAT_CHOICE:-1}" in
        1)
            WEBCHAT_WEB_DIR="/var/www/html/webchat"
            echo -e "${GREEN}WebChat will be installed to: $WEBCHAT_WEB_DIR${NC}"
            ;;
        2)
            WEBCHAT_WEB_DIR="/var/www/html"
            echo -e "${YELLOW}Warning: Installing directly in webroot${NC}"
            echo -e "${GREEN}WebChat will be installed to: $WEBCHAT_WEB_DIR${NC}"
            ;;
        3)
            read -p "Enter custom path: " CUSTOM_PATH
            WEBCHAT_WEB_DIR="${CUSTOM_PATH:-/var/www/html/webchat}"
            echo -e "${GREEN}WebChat will be installed to: $WEBCHAT_WEB_DIR${NC}"
            ;;
        4)
            WEBCHAT_WEB_DIR=""
            echo -e "${YELLOW}WebChat installation skipped${NC}"
            ;;
        *)
            WEBCHAT_WEB_DIR="/var/www/html/webchat"
            echo -e "${GREEN}WebChat will be installed to: $WEBCHAT_WEB_DIR (default)${NC}"
            ;;
    esac
}

# Check version consistency across project files
check_version_consistency() {
    echo -e "${YELLOW}Checking version consistency...${NC}"

    SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    VERSION_ISSUES=0

    # Get version from pyircx.py
    if [ -f "$SCRIPT_DIR/pyircx.py" ]; then
        PYIRCX_VERSION=$(grep "__version__" "$SCRIPT_DIR/pyircx.py" | head -1 | cut -d'"' -f2)
        echo -e "${GREEN}  pyircx.py version: $PYIRCX_VERSION${NC}"

        # Check against INSTALL_VERSION
        if [ "$PYIRCX_VERSION" != "$INSTALL_VERSION" ]; then
            echo -e "${RED}  ✗ Version mismatch: install.sh has $INSTALL_VERSION${NC}"
            VERSION_ISSUES=$((VERSION_ISSUES + 1))
        else
            echo -e "${GREEN}  ✓ install.sh version matches${NC}"
        fi

        # Check webadmin/index.php
        if [ -f "$SCRIPT_DIR/webadmin/index.php" ]; then
            WEBADMIN_VER=$(grep -o "pyIRCX v[0-9]\+\.[0-9]\+\.[0-9]\+" "$SCRIPT_DIR/webadmin/index.php" | head -1 | sed 's/pyIRCX v//')
            if [ "$PYIRCX_VERSION" != "$WEBADMIN_VER" ]; then
                echo -e "${RED}  ✗ Version mismatch: webadmin/index.php has $WEBADMIN_VER${NC}"
                VERSION_ISSUES=$((VERSION_ISSUES + 1))
            else
                echo -e "${GREEN}  ✓ webadmin/index.php version matches${NC}"
            fi
        fi

        # Check webchat/index.html
        if [ -f "$SCRIPT_DIR/webchat/index.html" ]; then
            WEBCHAT_VER=$(grep -o "v[0-9]\+\.[0-9]\+\.[0-9]\+</span>" "$SCRIPT_DIR/webchat/index.html" | head -1 | sed 's/v\(.*\)<\/span>/\1/')
            if [ "$PYIRCX_VERSION" != "$WEBCHAT_VER" ]; then
                echo -e "${RED}  ✗ Version mismatch: webchat/index.html has $WEBCHAT_VER${NC}"
                VERSION_ISSUES=$((VERSION_ISSUES + 1))
            else
                echo -e "${GREEN}  ✓ webchat/index.html version matches${NC}"
            fi
        fi

        if [ $VERSION_ISSUES -gt 0 ]; then
            echo -e "${YELLOW}  ⚠ Found $VERSION_ISSUES version inconsistency issue(s)${NC}"
            echo -e "${YELLOW}  This may indicate the installation files need to be updated${NC}"
            read -p "Continue anyway? (y/n) " -n 1 -r
            echo
            if [[ ! $REPLY =~ ^[Yy]$ ]]; then
                exit 1
            fi
        fi
    else
        echo -e "${YELLOW}  ⚠ pyircx.py not found, skipping version check${NC}"
    fi
}

# Check Python version
check_python() {
    echo -e "${YELLOW}Checking Python version...${NC}"

    if command -v python3 &> /dev/null; then
        PYTHON_VERSION=$(python3 -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')
        PYTHON_MAJOR=$(echo $PYTHON_VERSION | cut -d. -f1)
        PYTHON_MINOR=$(echo $PYTHON_VERSION | cut -d. -f2)

        if [ "$PYTHON_MAJOR" -ge 3 ] && [ "$PYTHON_MINOR" -ge 8 ]; then
            echo -e "${GREEN}Python $PYTHON_VERSION found${NC}"
            return 0
        fi
    fi

    echo -e "${RED}Error: Python 3.8+ is required${NC}"
    echo "Please install Python 3.8 or later"
    exit 1
}

# Install dependencies based on OS
install_dependencies() {
    local os=$(detect_os)
    echo -e "${YELLOW}Installing dependencies for $os...${NC}"

    case $os in
        ubuntu|debian|linuxmint|pop|elementary|zorin|kali|parrot|raspbian)
            apt-get update
            apt-get install -y python3 python3-pip python3-venv
            ;;
        fedora)
            dnf install -y python3 python3-pip
            ;;
        centos|rhel|rocky|almalinux|oracle|scientific)
            if [ -f /etc/centos-release ] || [ "$VERSION_ID" -lt 8 ]; then
                yum install -y python3 python3-pip
            else
                dnf install -y python3 python3-pip
            fi
            ;;
        arch|manjaro|endeavouros|garuda|artix)
            pacman -Sy --noconfirm python python-pip
            ;;
        opensuse*|sles|tumbleweed)
            zypper install -y python3 python3-pip
            ;;
        gentoo|funtoo)
            emerge --ask=n dev-lang/python dev-python/pip
            ;;
        void)
            xbps-install -Sy python3 python3-pip
            ;;
        alpine)
            apk add --no-cache python3 py3-pip
            ;;
        solus)
            eopkg install -y python3 pip
            ;;
        nixos)
            echo -e "${YELLOW}NixOS detected. Please add python3 and pip to your configuration.nix${NC}"
            echo "Example: environment.systemPackages = with pkgs; [ python3 python3Packages.pip ];"
            ;;
        clear-linux-os)
            swupd bundle-add python3-basic
            ;;
        mageia)
            urpmi python3 python3-pip
            ;;
        slackware)
            # Slackware typically has Python pre-installed
            echo -e "${GREEN}Slackware detected. Python should be pre-installed.${NC}"
            if ! command -v pip3 &> /dev/null; then
                echo -e "${YELLOW}pip not found. Installing pip...${NC}"
                python3 -m ensurepip --default-pip || python3 <(curl -sS https://bootstrap.pypa.io/get-pip.py)
            fi
            ;;
        *)
            echo -e "${YELLOW}Unknown OS ($os), attempting generic installation...${NC}"
            # Try to detect package manager and install
            if command -v apt-get &> /dev/null; then
                apt-get update && apt-get install -y python3 python3-pip python3-venv
            elif command -v dnf &> /dev/null; then
                dnf install -y python3 python3-pip
            elif command -v yum &> /dev/null; then
                yum install -y python3 python3-pip
            elif command -v pacman &> /dev/null; then
                pacman -Sy --noconfirm python python-pip
            elif command -v zypper &> /dev/null; then
                zypper install -y python3 python3-pip
            elif command -v apk &> /dev/null; then
                apk add --no-cache python3 py3-pip
            elif command -v emerge &> /dev/null; then
                emerge --ask=n dev-lang/python dev-python/pip
            else
                echo -e "${YELLOW}No supported package manager found.${NC}"
                echo -e "${YELLOW}Please ensure Python 3.8+ and pip are installed manually.${NC}"
            fi
            ;;
    esac
}

# Install Python packages
install_python_packages() {
    echo -e "${YELLOW}Installing Python packages...${NC}"

    pip3 install --upgrade pip
    pip3 install aiosqlite bcrypt pyotp cryptography

    echo -e "${GREEN}Python packages installed${NC}"
}

# Create service user
create_user() {
    echo -e "${YELLOW}Creating service user...${NC}"

    if id "$SERVICE_USER" &>/dev/null; then
        echo "User $SERVICE_USER already exists"
    else
        useradd --system --no-create-home --shell /usr/sbin/nologin "$SERVICE_USER"
        echo -e "${GREEN}User $SERVICE_USER created${NC}"
    fi

    # Add user to ssl-cert group for Let's Encrypt certificate access (Debian/Ubuntu)
    if getent group ssl-cert &>/dev/null; then
        if ! groups "$SERVICE_USER" 2>/dev/null | grep -q ssl-cert; then
            usermod -a -G ssl-cert "$SERVICE_USER"
            echo -e "${GREEN}User added to ssl-cert group${NC}"
        fi
    fi
}

# Create directories
create_directories() {
    echo -e "${YELLOW}Creating directories...${NC}"

    mkdir -p "$INSTALL_DIR"
    mkdir -p "$INSTALL_DIR/transcripts"
    mkdir -p "$CONFIG_DIR"

    echo -e "${GREEN}Directories created${NC}"
}

# Copy files
copy_files() {
    echo -e "${YELLOW}Copying files...${NC}"

    # Get the directory where this script is located
    SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

    # Copy main script and modules
    cp "$SCRIPT_DIR/pyircx.py" "$INSTALL_DIR/"
    cp "$SCRIPT_DIR/api.py" "$INSTALL_DIR/" 2>/dev/null || true
    cp "$SCRIPT_DIR/linking.py" "$INSTALL_DIR/"

    # Copy or create config
    if [ ! -f "$CONFIG_DIR/pyircx_config.json" ]; then
        if [ -f "$SCRIPT_DIR/pyircx_config.json" ]; then
            # Use provided config template
            cp "$SCRIPT_DIR/pyircx_config.json" "$CONFIG_DIR/"
            echo "Copied config template"
        else
            # Generate default config from pyircx.py
            echo "Generating default config..."
            python3 "$SCRIPT_DIR/generate_default_config.py" "$INSTALL_DIR/pyircx.py" "$CONFIG_DIR/pyircx_config.json"
        fi
    else
        echo "Config already exists, not overwriting"
    fi

    # Create symlink for config
    ln -sf "$CONFIG_DIR/pyircx_config.json" "$INSTALL_DIR/pyircx_config.json"

    echo -e "${GREEN}Files copied${NC}"
}

# Set permissions
set_permissions() {
    echo -e "${YELLOW}Setting permissions...${NC}"

    chown -R "$SERVICE_USER:$SERVICE_GROUP" "$INSTALL_DIR"
    chown -R "$SERVICE_USER:$SERVICE_GROUP" "$CONFIG_DIR"
    chmod 775 "$INSTALL_DIR"  # Group needs write for SQLite journal files
    chmod 775 "$CONFIG_DIR"  # Group needs write for web admin config edits
    chmod 750 "$INSTALL_DIR/transcripts"  # Keep transcripts private
    chmod 660 "$INSTALL_DIR/pyircx.db" 2>/dev/null || true  # Database group writable
    chmod 660 "$CONFIG_DIR/pyircx_config.json" 2>/dev/null || true  # Config group writable (for web admin)
    chmod 755 "$INSTALL_DIR/pyircx.py"
    chmod 755 "$INSTALL_DIR/api.py" 2>/dev/null || true
    chmod 755 "$INSTALL_DIR/linking.py" 2>/dev/null || true

    # Add web server user to pyircx group for database access
    # Detect web server user (apache, www-data, or http)
    WEB_USER=""
    if id apache &>/dev/null; then
        WEB_USER="apache"
    elif id www-data &>/dev/null; then
        WEB_USER="www-data"
    elif id http &>/dev/null; then
        WEB_USER="http"
    fi

    if [ -n "$WEB_USER" ]; then
        echo -e "${YELLOW}Adding $WEB_USER to $SERVICE_GROUP group for database access...${NC}"
        usermod -a -G "$SERVICE_GROUP" "$WEB_USER"
        echo -e "${GREEN}✓ Web server user added to group${NC}"

        # Restart PHP-FPM to apply group membership
        if systemctl is-active --quiet php-fpm 2>/dev/null; then
            echo -e "${YELLOW}Restarting PHP-FPM to apply group membership...${NC}"
            systemctl restart php-fpm
            echo -e "${GREEN}✓ PHP-FPM restarted${NC}"
        fi
    fi

    echo -e "${GREEN}Permissions set${NC}"
}

# Install Web Admin Panel
install_web_admin() {
    echo -e "${YELLOW}Installing Web Administration Panel...${NC}"

    # Check if path is set
    if [ -z "$WEB_ADMIN_DIR" ]; then
        echo -e "${RED}Error: WEB_ADMIN_DIR not set${NC}"
        return 1
    fi

    local os=$(detect_os)
    SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

    # Install Apache and PHP based on OS
    case "$os" in
        fedora|rhel|centos|rocky|almalinux|oracle|scientific)
            echo -e "${YELLOW}Installing Apache and PHP...${NC}"
            dnf install -y httpd php php-fpm php-json php-mbstring || yum install -y httpd php php-fpm php-json php-mbstring
            systemctl enable --now httpd
            systemctl enable --now php-fpm
            ;;
        debian|ubuntu|linuxmint|pop|elementary|zorin|kali|parrot|raspbian)
            echo -e "${YELLOW}Installing Apache and PHP...${NC}"
            apt-get update
            apt-get install -y apache2 php php-fpm php-json php-mbstring
            a2enmod rewrite
            systemctl enable --now apache2
            ;;
        arch|manjaro|endeavouros|garuda)
            echo -e "${YELLOW}Installing Apache and PHP...${NC}"
            pacman -S --noconfirm apache php php-fpm
            systemctl enable --now httpd
            systemctl enable --now php-fpm
            ;;
        *)
            echo -e "${YELLOW}Please install Apache and PHP manually for your OS${NC}"
            return 1
            ;;
    esac

    # Create web admin directory
    mkdir -p "$WEB_ADMIN_DIR"

    # Copy web admin files
    if [ -d "$SCRIPT_DIR/webadmin" ]; then
        cp "$SCRIPT_DIR/webadmin"/*.php "$WEB_ADMIN_DIR/" 2>/dev/null || true
        cp "$SCRIPT_DIR/webadmin"/*.js "$WEB_ADMIN_DIR/" 2>/dev/null || true
        cp "$SCRIPT_DIR/webadmin"/*.css "$WEB_ADMIN_DIR/" 2>/dev/null || true
        cp "$SCRIPT_DIR/webadmin"/.htaccess "$WEB_ADMIN_DIR/" 2>/dev/null || true
    else
        echo -e "${RED}Web admin files not found${NC}"
        return 1
    fi

    # Set ownership to apache user
    chown -R apache:apache "$WEB_ADMIN_DIR"
    chmod 755 "$WEB_ADMIN_DIR"
    chmod 644 "$WEB_ADMIN_DIR"/*.php 2>/dev/null || true
    chmod 644 "$WEB_ADMIN_DIR"/*.js 2>/dev/null || true
    chmod 644 "$WEB_ADMIN_DIR"/*.css 2>/dev/null || true
    chmod 644 "$WEB_ADMIN_DIR"/.htaccess 2>/dev/null || true

    # Add apache user to systemd-journal group for log access
    usermod -a -G systemd-journal apache 2>/dev/null || true

    # Configure SELinux if enabled
    if command -v getenforce &>/dev/null && [ "$(getenforce)" != "Disabled" ]; then
        echo -e "${YELLOW}SELinux detected, installing policies...${NC}"
        install_selinux
    fi

    # Install polkit rules
    install_polkit

    echo -e "${GREEN}Web Admin Panel installed successfully!${NC}"
    echo ""
    echo "Access at: http://localhost/webadmin/"
    echo "Login with your IRC staff account (administrators only)"
    echo ""
}

# Install SELinux policies
install_selinux() {
    SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

    if [ ! -d "$SCRIPT_DIR/selinux" ]; then
        echo -e "${YELLOW}SELinux policy files not found, skipping${NC}"
        return 0
    fi

    echo -e "${YELLOW}Installing SELinux policies...${NC}"

    cd "$SCRIPT_DIR/selinux"

    # Compile and install httpd-systemd policy
    if [ -f pyircx-httpd-systemd.te ]; then
        checkmodule -M -m -o pyircx-httpd-systemd.mod pyircx-httpd-systemd.te
        semodule_package -o pyircx-httpd-systemd.pp -m pyircx-httpd-systemd.mod
        semodule -i pyircx-httpd-systemd.pp
        echo -e "${GREEN}✓ httpd-systemd policy installed${NC}"
    fi

    # Compile and install httpd-journal policy
    if [ -f pyircx-httpd-journal-v3.te ]; then
        checkmodule -M -m -o pyircx-httpd-journal-v3.mod pyircx-httpd-journal-v3.te
        semodule_package -o pyircx-httpd-journal-v3.pp -m pyircx-httpd-journal-v3.mod
        semodule -i pyircx-httpd-journal-v3.pp
        echo -e "${GREEN}✓ httpd-journal policy installed${NC}"
    fi

    cd - > /dev/null

    # Configure SELinux file contexts (comprehensive configuration)
    if command -v semanage &> /dev/null && command -v restorecon &> /dev/null; then
        echo -e "${YELLOW}Configuring SELinux file contexts...${NC}"

        # /opt/pyircx - Main installation (read-write for web admin API)
        semanage fcontext -d -t httpd_sys_rw_content_t "/opt/pyircx(/.*)?" 2>/dev/null || true
        semanage fcontext -a -t httpd_sys_rw_content_t "/opt/pyircx(/.*)?" 2>/dev/null || true

        # /etc/pyircx - Configuration directory (read-write for web admin config editor)
        #               EXCEPT webchat.conf which needs etc_t for systemd EnvironmentFile
        semanage fcontext -d -t httpd_sys_rw_content_t "/etc/pyircx(/.*)?" 2>/dev/null || true
        semanage fcontext -a -t httpd_sys_rw_content_t "/etc/pyircx(/.*)?" 2>/dev/null || true

        # /etc/pyircx/webchat.conf - SystemD EnvironmentFile (MUST be etc_t, NOT httpd_sys_rw_content_t)
        # This overrides the previous rule specifically for webchat.conf
        semanage fcontext -d -t etc_t "/etc/pyircx/webchat\.conf" 2>/dev/null || true
        semanage fcontext -a -t etc_t "/etc/pyircx/webchat\.conf" 2>/dev/null || true

        # WebAdmin - only if directory exists or will be created
        if [ -n "$WEB_ADMIN_DIR" ] || [ -d "/var/www/html/webadmin" ]; then
            ADMIN_PATH="${WEB_ADMIN_DIR:-/var/www/html/webadmin}"
            semanage fcontext -d -t httpd_sys_rw_content_t "$ADMIN_PATH(/.*)?" 2>/dev/null || true
            semanage fcontext -a -t httpd_sys_rw_content_t "$ADMIN_PATH(/.*)?" 2>/dev/null || true
        fi

        # WebChat - only if directory exists or will be created
        if [ -n "$WEBCHAT_WEB_DIR" ] || [ -d "/var/www/html/webchat" ]; then
            CHAT_PATH="${WEBCHAT_WEB_DIR:-/var/www/html/webchat}"
            semanage fcontext -d -t httpd_sys_content_t "$CHAT_PATH(/.*)?" 2>/dev/null || true
            semanage fcontext -a -t httpd_sys_content_t "$CHAT_PATH(/.*)?" 2>/dev/null || true
        fi

        # Apply all contexts
        restorecon -Rv /opt/pyircx 2>/dev/null || true
        restorecon -Rv /etc/pyircx 2>/dev/null || true
        [ -n "$WEB_ADMIN_DIR" ] && [ -d "$WEB_ADMIN_DIR" ] && restorecon -Rv "$WEB_ADMIN_DIR" 2>/dev/null || true
        [ -n "$WEBCHAT_WEB_DIR" ] && [ -d "$WEBCHAT_WEB_DIR" ] && restorecon -Rv "$WEBCHAT_WEB_DIR" 2>/dev/null || true

        # CRITICAL: Explicitly fix webchat.conf after global restorecon
        if [ -f "/etc/pyircx/webchat.conf" ]; then
            chcon -t etc_t "/etc/pyircx/webchat.conf" 2>/dev/null || true
            echo -e "${GREEN}✓ SELinux context fixed for webchat.conf (etc_t)${NC}"
        fi

        echo -e "${GREEN}✓ SELinux file contexts configured${NC}"
    fi

    echo -e "${GREEN}SELinux policies installed${NC}"
}

# Install Polkit rules
install_polkit() {
    SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

    if [ ! -d "$SCRIPT_DIR/polkit" ]; then
        echo -e "${YELLOW}Polkit rules not found, skipping${NC}"
        return 0
    fi

    echo -e "${YELLOW}Installing Polkit authorization rules...${NC}"

    # Copy polkit rules
    if [ -f "$SCRIPT_DIR/polkit/10-pyircx-admin.rules" ]; then
        cp "$SCRIPT_DIR/polkit/10-pyircx-admin.rules" /etc/polkit-1/rules.d/
        chown root:root /etc/polkit-1/rules.d/10-pyircx-admin.rules
        chmod 644 /etc/polkit-1/rules.d/10-pyircx-admin.rules

        # Reload polkit
        systemctl reload polkit 2>/dev/null || true

        echo -e "${GREEN}Polkit rules installed${NC}"
    fi
}


# Initialize database
initialize_database() {
    echo -e "${YELLOW}Initializing database...${NC}"

    SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    DB_PATH="$INSTALL_DIR/pyircx.db"

    # Check if database already exists
    if [ -f "$DB_PATH" ]; then
        echo -e "${YELLOW}Database already exists, skipping initialization${NC}"
        return 0
    fi

    # Use init_database.py if available
    if [ -f "$SCRIPT_DIR/init_database.py" ]; then
        echo -e "${YELLOW}Creating database with init_database.py...${NC}"
        python3 "$SCRIPT_DIR/init_database.py" "$DB_PATH" --admin-username admin --admin-password changeme

        # Set ownership and permissions
        chown "$SERVICE_USER:$SERVICE_GROUP" "$DB_PATH"
        chmod 660 "$DB_PATH"

        echo -e "${GREEN}✓ Database initialized${NC}"
    else
        echo -e "${YELLOW}⚠ init_database.py not found${NC}"
        echo -e "${YELLOW}Database will be created on first service start${NC}"
    fi
}

# Install systemd service
install_systemd() {
    echo -e "${YELLOW}Installing systemd service...${NC}"

    SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

    # Copy service file
    cp "$SCRIPT_DIR/pyircx.service" /etc/systemd/system/

    # Copy certbot renewal service/timer if available
    if [ -f "$SCRIPT_DIR/pyircx-certbot-renew.service" ]; then
        cp "$SCRIPT_DIR/pyircx-certbot-renew.service" /etc/systemd/system/
        cp "$SCRIPT_DIR/pyircx-certbot-renew.timer" /etc/systemd/system/
    fi

    # Reload systemd
    systemctl daemon-reload

    # Enable service (but don't start yet - will start after database is ready)
    systemctl enable pyircx

    echo -e "${GREEN}Systemd service installed${NC}"
}

# Start pyIRCX service
start_service() {
    echo -e "${YELLOW}Starting pyIRCX service...${NC}"

    systemctl start pyircx
    sleep 2

    if systemctl is-active --quiet pyircx; then
        echo -e "${GREEN}✓ Service started successfully${NC}"
        # Fix database permissions after service access
        chmod 660 "$INSTALL_DIR/pyircx.db" 2>/dev/null || true
        chmod 775 "$INSTALL_DIR" 2>/dev/null || true
    else
        echo -e "${RED}✗ Service failed to start${NC}"
        echo -e "${YELLOW}Check logs: journalctl -u pyircx -n 50${NC}"
        return 1
    fi

    echo ""
    echo "Service commands:"
    echo "  systemctl status pyircx   - Check status"
    echo "  systemctl restart pyircx  - Restart server"
    echo "  systemctl stop pyircx     - Stop server"
}

# Install WebChat browser client
install_webchat() {
    echo -e "${YELLOW}Installing WebChat browser client...${NC}"

    # Check if path is set
    if [ -z "$WEBCHAT_WEB_DIR" ]; then
        echo -e "${RED}Error: WEBCHAT_WEB_DIR not set${NC}"
        return 1
    fi

    SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

    # Check for websockets Python module
    if ! python3 -c "import websockets" 2>/dev/null; then
        echo -e "${YELLOW}Installing Python websockets module...${NC}"
        pip3 install websockets
    fi

    # Create webchat backend directory
    mkdir -p "$INSTALL_DIR/webchat"

    # Create webchat web directory
    mkdir -p "$WEBCHAT_WEB_DIR"

    # Copy webchat files
    if [ -d "$SCRIPT_DIR/webchat" ]; then
        # Backend gateway goes to /opt/pyircx/webchat
        cp "$SCRIPT_DIR/webchat/gateway.py" "$INSTALL_DIR/webchat/"
        chmod 755 "$INSTALL_DIR/webchat/gateway.py"

        # Frontend files go to /var/www/html/webchat
        cp "$SCRIPT_DIR/webchat/index.html" "$WEBCHAT_WEB_DIR/"
        cp "$SCRIPT_DIR/webchat/config.js" "$WEBCHAT_WEB_DIR/"
        cp "$SCRIPT_DIR/webchat/favicon.svg" "$WEBCHAT_WEB_DIR/" 2>/dev/null || true
        chmod 644 "$WEBCHAT_WEB_DIR/index.html"
        chmod 644 "$WEBCHAT_WEB_DIR/config.js"
        chmod 644 "$WEBCHAT_WEB_DIR/favicon.svg" 2>/dev/null || true
    else
        echo -e "${RED}WebChat files not found in $SCRIPT_DIR/webchat${NC}"
        return 1
    fi

    # Set permissions
    chown -R "$SERVICE_USER:$SERVICE_GROUP" "$INSTALL_DIR/webchat"

    # Set web directory permissions (web server user)
    if id apache &>/dev/null; then
        chown -R apache:apache "$WEBCHAT_WEB_DIR"
    elif id www-data &>/dev/null; then
        chown -R www-data:www-data "$WEBCHAT_WEB_DIR"
    elif id http &>/dev/null; then
        chown -R http:http "$WEBCHAT_WEB_DIR"
    fi

    # Create webchat config file
    if [ ! -f "$CONFIG_DIR/webchat.conf" ]; then
        cat > "$CONFIG_DIR/webchat.conf" <<EOF
# pyIRCX WebChat Gateway Configuration
# This file is sourced by the systemd service

# WebSocket server settings
WS_PORT=8765
WS_HOST=0.0.0.0

# IRC server connection
IRC_HOST=localhost
IRC_PORT=6667

# WEBIRC password (must match pyircx.py security.webirc.hosts config)
# IMPORTANT: Change this in production!
WEBIRC_PASS=changeme
EOF
        chown "$SERVICE_USER:$SERVICE_GROUP" "$CONFIG_DIR/webchat.conf"
        chmod 640 "$CONFIG_DIR/webchat.conf"
    fi

    # Copy systemd service
    if [ -f "$SCRIPT_DIR/pyircx-webchat.service" ]; then
        cp "$SCRIPT_DIR/pyircx-webchat.service" /etc/systemd/system/
        systemctl daemon-reload
        # Enable and start the webchat service
        systemctl enable pyircx-webchat
        systemctl start pyircx-webchat
    fi

    # Configure firewall for WebSocket port
    if command -v firewall-cmd &>/dev/null; then
        echo -e "${YELLOW}Configuring firewall for WebChat...${NC}"
        firewall-cmd --permanent --add-port=8765/tcp 2>/dev/null || true
        firewall-cmd --reload 2>/dev/null || true
    elif command -v ufw &>/dev/null; then
        ufw allow 8765/tcp 2>/dev/null || true
    fi

    echo -e "${GREEN}WebChat installed and started!${NC}"
    echo ""
    echo "WebChat backend: $INSTALL_DIR/webchat/"
    echo "WebChat frontend: $WEBCHAT_WEB_DIR/"
    echo "Configuration: $CONFIG_DIR/webchat.conf"
    echo ""
    echo "Service commands:"
    echo "  systemctl status pyircx-webchat   - Check status"
    echo "  systemctl restart pyircx-webchat  - Restart gateway"
    echo ""
    echo "Access WebChat at: http://localhost/webchat/"
    echo "WebSocket endpoint: ws://localhost:8765"
    echo ""
    echo "For HTTPS/WSS setup, see: apache/ssl-webchat.conf.example"
    echo ""
}

# Main installation
main() {
    echo ""
    echo "========================================"
    echo "  pyIRCX Installation Script"
    echo "========================================"
    echo ""

    check_root
    check_python
    check_version_consistency

    echo ""
    read -p "Install to $INSTALL_DIR? [Y/n] " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Nn]$ ]]; then
        read -p "Enter installation directory: " INSTALL_DIR
    fi

    install_dependencies
    install_python_packages
    create_user
    create_directories
    copy_files
    set_permissions
    initialize_database
    install_systemd
    start_service

    echo ""
    echo "========================================"
    echo -e "${GREEN}  Core Installation Complete!${NC}"
    echo "========================================"
    echo ""
    echo "Configuration: $CONFIG_DIR/pyircx_config.json"
    echo "Installation:  $INSTALL_DIR"
    echo "Database:      $INSTALL_DIR/pyircx.db"
    echo "Logs:          journalctl -u pyircx -f"
    echo ""
    echo -e "${YELLOW}Default Admin Account:${NC}"
    echo "  Username: admin"
    echo "  Password: changeme"
    echo ""
    echo -e "${RED}*** CHANGE THE DEFAULT PASSWORD IMMEDIATELY ***${NC}"
    echo ""
    echo "How to change password:"
    echo "  Option 1 - Via command line:"
    echo "    python3 $INSTALL_DIR/api.py change-staff-password admin YourNewPassword"
    echo ""
    echo "  Option 2 - Via IRC client:"
    echo "    /QUOTE PASS admin:changeme"
    echo "    /STAFF PASS admin YourNewPassword"
    echo ""
    echo -e "${GREEN}Essential Commands:${NC}"
    echo "  systemctl status pyircx   - Check server status"
    echo "  systemctl restart pyircx  - Restart server"
    echo "  systemctl stop pyircx     - Stop server"
    echo "  journalctl -u pyircx -f   - View live logs"
    echo ""
    echo -e "${GREEN}Database Management:${NC}"
    echo "  Regenerate database: python3 init_database.py $INSTALL_DIR/pyircx.db --force"
    echo "  Backup database: cp $INSTALL_DIR/pyircx.db backup_$(date +%Y%m%d).db"
    echo ""
    echo "Default IRC ports: 6667 (plain), 6697 (SSL if configured)"
    echo ""
    echo "========================================"
    echo -e "${YELLOW}Optional: Web Server Setup (Apache/httpd)${NC}"
    echo "========================================"
    echo ""
    echo "Setting up Apache/httpd is recommended before SSL configuration."
    echo "This configures Apache for WebChat, WebAdmin, and SSL certificates."
    echo ""
    echo "The setup script will:"
    echo "  - Install Apache/httpd and PHP (if needed)"
    echo "  - Configure virtual hosts for WebChat and WebAdmin"
    echo "  - Set up proper permissions and SELinux contexts"
    echo "  - Enable required Apache modules"
    echo ""
    read -p "Set up Apache/httpd now? [Y/n] " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Nn]$ ]]; then
        if [ -f "setup_apache.sh" ]; then
            echo ""
            echo "Running Apache setup..."
            ./setup_apache.sh
        else
            echo -e "${YELLOW}setup_apache.sh not found in current directory${NC}"
            echo "You can run it later: sudo ./setup_apache.sh"
        fi
    else
        echo ""
        echo "Apache setup skipped. You can run it later with:"
        echo "  sudo ./setup_apache.sh"
    fi
    echo ""
    echo "========================================"
    echo -e "${YELLOW}Optional: SSL/TLS Certificate Setup${NC}"
    echo "========================================"
    echo ""
    echo "Would you like to set up SSL/TLS now?"
    echo "  - Let's Encrypt (free, automatic)"
    echo "  - Self-signed (for testing)"
    echo "  - Skip (configure manually later)"
    echo ""
    read -p "Set up SSL/TLS now? [y/N] " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        if [ -f "setup_ssl.sh" ]; then
            ./setup_ssl.sh "$CONFIG_DIR/pyircx_config.json"
        else
            echo -e "${YELLOW}setup_ssl.sh not found, skipping SSL setup${NC}"
            echo "You can run it later: sudo ./setup_ssl.sh"
        fi
    else
        echo ""
        echo "SSL/TLS can be set up later with:"
        echo "  sudo ./setup_ssl.sh"
    fi
    echo ""
    echo "========================================"
    echo -e "${YELLOW}Optional: Web Administration Panel${NC}"
    echo "========================================"
    echo ""
    echo "The Web Admin Panel provides a browser-based interface for"
    echo "managing the IRC server. Requires Apache and PHP."
    echo ""
    read -p "Install Web Administration Panel? [y/N] " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        prompt_webadmin_path
        if [ -n "$WEB_ADMIN_DIR" ]; then
            install_web_admin
        fi
    fi

    echo ""
    echo "========================================"
    echo -e "${YELLOW}Optional: WebChat (Browser IRC Client)${NC}"
    echo "========================================"
    echo ""
    echo "WebChat provides a browser-based IRC client that connects"
    echo "via WebSocket. Requires a web server for HTTPS."
    echo ""
    read -p "Install WebChat browser client? [y/N] " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        prompt_webchat_path
        if [ -n "$WEBCHAT_WEB_DIR" ]; then
            install_webchat
        fi
    fi

    # Save installation configuration
    save_install_config
}

# Uninstall function
uninstall() {
    echo ""
    echo "========================================"
    echo "  pyIRCX Uninstallation"
    echo "========================================"
    echo ""

    check_root

    echo -e "${YELLOW}Stopping service...${NC}"
    systemctl stop pyircx 2>/dev/null || true
    systemctl disable pyircx 2>/dev/null || true

    echo -e "${YELLOW}Removing files...${NC}"
    rm -f /etc/systemd/system/pyircx.service
    systemctl daemon-reload

    read -p "Remove installation directory $INSTALL_DIR? [y/N] " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        rm -rf "$INSTALL_DIR"
    fi

    read -p "Remove configuration $CONFIG_DIR? [y/N] " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        rm -rf "$CONFIG_DIR"
    fi

    read -p "Remove user $SERVICE_USER? [y/N] " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        userdel "$SERVICE_USER" 2>/dev/null || true
    fi

    echo -e "${GREEN}Uninstallation complete${NC}"
}

# Parse arguments
case "${1:-}" in
    uninstall|remove)
        uninstall
        ;;
    *)
        main
        ;;
esac
