#!/bin/bash
# EVENT System Test Script for pyIRCX

echo "==================================="
echo "pyIRCX EVENT System Test"
echo "==================================="
echo ""
echo "This test will verify the EVENT system is working correctly."
echo ""
echo "Prerequisites:"
echo "  1. You must connect via SSL (port 6697)"
echo "  2. You must authenticate as a staff member (ADMIN or SYSOP)"
echo "  3. You must enable IRCX mode"
echo ""
echo "Expected EVENT format:"
echo "  :servername EVENT <timestamp> <class> <action> <channel> <user!ident@host> <ip:port> <data>"
echo ""
echo "==================================="
echo "Test Steps:"
echo "==================================="
echo ""
echo "1. Connect to server via SSL:"
echo "   openssl s_client -connect atlas.jdlewis.net:6697 -quiet"
echo ""
echo "2. Authenticate (replace with your credentials):"
echo "   PASS jdlewis <password>"
echo "   NICK YourNick"
echo "   USER yourusername 0 * :Your Name"
echo ""
echo "3. Enable IRCX mode:"
echo "   IRCX"
echo "   (You should see: :atlas.jdlewis.net 800 YourNick 1 0 AUTH 512 *)"
echo ""
echo "4. Subscribe to events:"
echo "   EVENT ADD CONNECT *!*@*"
echo "   (You should see: :atlas.jdlewis.net 806 YourNick CONNECT *!*@*)"
echo ""
echo "   EVENT ADD MEMBER *!*@*"
echo "   (You should see: :atlas.jdlewis.net 806 YourNick MEMBER *!*@*)"
echo ""
echo "   EVENT LIST"
echo "   (You should see your subscriptions)"
echo ""
echo "5. Trigger events by opening a SECOND connection:"
echo "   - Connect another client"
echo "   - JOIN #test"
echo "   - PART #test"
echo "   - QUIT"
echo ""
echo "6. In the FIRST connection, you should see EVENT messages like:"
echo "   :atlas.jdlewis.net EVENT 1737239520 CONNECT USER LOGON Nick!user@host ip:port 0.0.0.0:0"
echo "   :atlas.jdlewis.net EVENT 1737239521 MEMBER JOIN #test Nick!user@host ip:port 0.0.0.0:0"
echo "   :atlas.jdlewis.net EVENT 1737239522 MEMBER PART #test Nick!user@host ip:port 0.0.0.0:0"
echo "   :atlas.jdlewis.net EVENT 1737239523 USER LOGOFF Nick!user@host ip:port 0.0.0.0:0"
echo ""
echo "==================================="
echo "Debug Commands:"
echo "==================================="
echo ""
echo "Check server logs for EVENT activity:"
echo "  ssh atlas.jdlewis.net \"sudo journalctl -u pyircx -f | grep -E 'EVENT|fire_trap'\""
echo ""
echo "Check if your user is authenticated as staff:"
echo "  /WHOIS YourNick"
echo "  (Should show modes including +a for admin or +o for operator)"
echo ""
echo "Check if IRCX mode is enabled:"
echo "  /MODE YourNick"
echo "  (Should show +x in the mode list)"
echo ""
